### ISSUE TITLE
Error in project

### ISSUE THREAD

**Issue by mallowigi** [davidsommer/IconViewer#3]
I got an error in my project, and the icons cease to render in the Sidebar

IntelliJ IDEA 2017.3 EAP (Ultimate Edition)
Build #IU-173.3188.16, built on October 10, 2017
IntelliJ IDEA EAP User
Expiration date: November 9, 2017
JRE: 1.8.0_152-release-1024-b5 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13

Coordinate out of bounds!
java.lang.ArrayIndexOutOfBoundsException: Coordinate out of bounds!
	at sun.awt.image.IntegerInterleavedRaster.getDataElements(IntegerInterleavedRaster.java:264)
	at sun.awt.image.OffScreenImageSource.sendPixels(OffScreenImageSource.java:136)
	at sun.awt.image.OffScreenImageSource.produce(OffScreenImageSource.java:187)
	at sun.awt.image.OffScreenImageSource.addConsumer(OffScreenImageSource.java:66)
	at sun.awt.image.OffScreenImageSource.startProduction(OffScreenImageSource.java:80)
	at java.awt.image.FilteredImageSource.startProduction(FilteredImageSource.java:183)
	at sun.awt.image.ImageRepresentation.startProduction(ImageRepresentation.java:732)
	at sun.awt.image.ToolkitImage.addWatcher(ToolkitImage.java:221)
	at sun.awt.image.ToolkitImage.getProperty(ToolkitImage.java:169)
	at javax.swing.ImageIcon.<init>(ImageIcon.java:240)
	at ch.dasoft.iconviewer.ImageIconProvider.getIcon(ImageIconProvider.java:37)
	at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:42)
	at com.intellij.psi.impl.ElementBase.computeIconNow(ElementBase.java:118)
	at com.intellij.psi.impl.ElementBase.lambda$static$0(ElementBase.java:59)
	at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.java:277)
	at com.intellij.ui.DeferredIconImpl.b(DeferredIconImpl.java:163)
	at com.intellij.ui.IconDeferrerImpl.evaluateDeferred(IconDeferrerImpl.java:111)
	at com.intellij.ui.DeferredIconImpl.a(DeferredIconImpl.java:163)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1132)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:85)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:141)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:534)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:479)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:139)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:85)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:106)
	at com.intellij.ui.DeferredIconImpl.a(DeferredIconImpl.java:162)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by davidsommer** [comment]
@mallowigi do you have the icon that it tried to render? that would help to fix the bug...
